### PR TITLE
[TESTING] Fixed some problems with admin page test, made them more neat

### LINKED ISSUE #3705: [TESTING] Create front-end test for the admin users overview page
Create front-end tests for all features on the `/admin/users` page:

- 'Return to admin page' button
- 'View all users' button
- Visible attributes - checking on/off attributes
- Filtering options - filtering on created/last login/username/etc..

### PR DESCRIPTION
**Pull request by martinj2001**
**Description**

Added cypress.env variables to make it the code base more maintainable
Added id's to buttons
Added goToAdminUsersPage

**Fixes _issue or discussion number_**
Fixes #3705 

**How to test**
Run in the /tests folder:
```
npx cypress run --spec cypress/e2e/admin_page
```

### CODE REVIEW

**Review by JimmyOei — CHANGES_REQUESTED** [review]
Perfect, one last thing: most id's (if i am correct) are in the following format: e.g. "returnbutton" -> "return_button", "usersbutton" -> "users_button".

**Comment by martinj2001** [comment]
Fixed that!

**Review by JimmyOei — APPROVED** [review]

File: tests/cypress/e2e/tools/navigation/nav.js [hunk 1]
```diff
@@ -52,7 +54,8 @@ export function goToHedyLevel2Page()
 
 export function goToAdminUsersPage()
 {
-    return goToPage(Cypress.env('admin/users'));
+    loginForAdmin();
```
Comment (Felienne) [inline tests/cypress/e2e/tools/navigation/nav.js:57]: Nice, this is a lot more readable and maintainable!
