### PR TITLE
🪲 Fix bug in custom Skulpt module extensions

### LINKED ISSUE #5729: 🪲Turtle commands in if-pressed statements terminate unexpectedly
**Describe the bug**
If the body of an if-pressed statement contains multiple turtle commands, only the first gets executed

**Paste the Hedy code & level**
Level 12:
```
if x is pressed
    forward 90
    turn 90
    forward 90
else
    forward 90
    turn -90
    forward 90
```

**Add a screenshot (optional)**
Screenshot 2024-08-29 at 17 06 38

The issue seems to be related to #5681. We decided to go with the not-so-great solution of removing the time.sleep statements. Obviously, we cannot drop the forward or turn command here.

### PR DESCRIPTION
**Pull request by boryanagoncharenko**
This PR addresses the following issues:
- When the body of an if-pressed command contains more than one turtle functions, only the first one will be executed.
- When the body of an if-pressed command contains time.sleep(), the execution would terminate when reaching this line.

Fixes  #5729 #5681

**How to test**
Run locally, go to level 15 and run the following scenarios:
1. Check that the code below outputs all items in the list. Note that they should not appear at once, but with a tiny delay in between:
```
lijstje is "1", "2", "3", "4", "5"
if x is pressed
    for dier in lijstje
        print dier
else
    print 'onbekend dier'
```
2. Check that when pressing x, all statements are executed. Note that the waiting-for-key-press modal should appear and then disappear while the action is being executed. Note that pressing the x button while the turtle is moving should not trigger a new run. If an error occurs, the keys should not be animated anymore.
```
i = 0
while i < 20
    if x is pressed
        turn 10
        color 'blue'
        turn 90
        forward 50
        color 'red'
        turn 90
        forward 50
        color 'orange'
        turn 90
        forward 50
        color 'green'
        turn 90
        forward 50
    else
        turn -15
        color 'blue'
        turn -90
        forward 50
        color 'red'
        turn -90
        forward 50
        color 'orange'
        turn -90
        forward 50
        color 'green'
        turn -90
        forward 50
    i = i + 1
```

### CODE REVIEW

File: static/vendor/skulpt-stdlib-extensions.js [hunk 1]
```diff
@@ -21,49 +21,71 @@ var $builtinmodule = function (name) {
...
-    } 
+    }
+
+    var ongoingIfPressedCall = false;
+
+    function callIfPressedFunc(name, resolve, reject) {
+      var f = Sk.misceval.loadname(name, Sk.globals);
+      var currentProgram = window.sessionStorage.getItem("currentProgram");
+
+      Sk.misceval.asyncToPromise(() =>
```
Comment (jpelay) [inline static/vendor/skulpt-stdlib-extensions.js:32]: Ahh it makes sense! AsyncToPromise is the one to use

**Review by jpelay — APPROVED** [review]
It works!
