### PR TITLE
🪲 Fix keyword language switcher when URL parameters are set to non-English

### LINKED ISSUE #6157: 🪲 Cannot change the keyword language after changing the UI language (twice)
**Describe the bug**
Cannot change the keyword language after changing the UI language non-English -> English -> non-English. 

How to reproduce:
1. Go to the Hedy course https://www.hedy.org/hedy
2. Change the UI language to something else than English e.g. Español (I see https://www.hedy.org/hedy#default in URL)
3. Change the UI language to English (I see https://www.hedy.org/hedy?language=en&keyword_language=en#default in URL). 
4. Change the UI language to something else than English e.g. Español (I see https://www.hedy.org/hedy?language=es&keyword_language=es#default in URL)
5. Change the keyword language - no result. Keywords are always in Español. 

**Workaround**
Change the keyword language using the `keyword_language` parameter in URL, e.g. replace `https://www.hedy.org/hedy?language=es&keyword_language=es#default` with `https://www.hedy.org/hedy?language=es&keyword_language=en#default` (`keyword_language=en` instead of `keyword_language=es`).

**Paste the Hedy code & level**
nothing here

**Add a screenshot (optional)**
Image

**What machine and browser you were using (optional)**
- MacOS 15.3, Firefox 134
- MacOS 15.3, Safari 18.3

### PR DESCRIPTION
**Pull request by brianpeiris**
Fixes #6157

When switching the keyword language with `toggle_keyword_language`, the code in `app.ts` is supposed to check if the app is in an iframe, but it was not doing so correctly, so it ended up reloading the page, which overrode the `urlParams` changes in the code immediately above it. This PR changes the conditional so that it correctly detects whether the app is in an iframe.

**How to test**

Follow these steps to verify this PR works as intended:

* Visit http://localhost:8080/hedy
* Change the UI language to Español
* Change the UI language back to English
* Change the UI language to Español again
* Toggle the keyword language to Inglés
* See that the code keyword changes from `imprimir` to `print`

Test that the slides still reload correctly when changing the keyword language:
* Login as teacher1
* In the account settings, change the "Preferred language" to Español
* Visit http://localhost:8080/slides#/1/0/0
* Change the keyword language to Español
* See that the page refreshes and that the code and the slide title changes to `imprimir`

**Checklist**
Done? Check if you have it all in place using this list: (mark with x if done)

- [x] Contains one of the PR categories in the name
- [x] Describes changes in the format above
- [x] Links to an existing issue or discussion
- [x] Has a "How to test" section

### CODE REVIEW

File: static/js/app.ts [hunk 1]
```diff
@@ -1435,7 +1435,7 @@ export function toggle_keyword_language(current_lang: string, new_lang: string)
       window.open(hash, "_self");
 
       // if in iframe, reload the topper window level.
-      if (window.top && !(window as any).Cypress) {
+      if (window.top && window.top !== window && !(window as any).Cypress) {
```
Comment (jpelay) [inline static/js/app.ts:1438]: Nice! Thank you so much for this fix, Brian! This is awesome stuff, we appreciate your contributions a lot, sorry I havent been able to review them sooner.

**Review by jpelay — APPROVED** [review]
